# Generated by Django 4.1.5 on 2023-01-05 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval_added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.TextField(max_length=25, verbose_name='Красивое название')),
                ('title_added', models.TextField(max_length=25, verbose_name='Название')),
                ('other_titles', models.TextField(max_length=25, verbose_name='Другие комментарии')),
                ('connect', models.TextField(max_length=25)),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('winter', models.TextField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=5)),
                ('summer', models.TextField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=5)),
                ('autumn', models.TextField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=5)),
                ('spring', models.TextField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=5)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'В работе'), ('accepted', 'информация принята'), ('rejected', 'информация не принята')], default='new', max_length=25, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval_areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_area', models.TextField(max_length=255, verbose_name='Горный хребет')),
            ],
        ),
        migrations.CreateModel(
            name='Spr_activities_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_types', models.TextField(max_length=25, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.EmailField(max_length=20, unique=True, verbose_name='Почта пользователя')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, upload_to='files/', verbose_name='Фото')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.pereval_added')),
            ],
        ),
        migrations.AddField(
            model_name='pereval_added',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.pereval_areas', verbose_name='Горный хребет'),
        ),
        migrations.AddField(
            model_name='pereval_added',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.users'),
        ),
        migrations.AddField(
            model_name='pereval_added',
            name='coord_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.coords'),
        ),
    ]
