# Generated by Django 4.1.5 on 2023-01-07 12:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0003_remove_users_user_name_users_fam_users_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
