# Generated by Django 4.1.5 on 2023-01-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0005_alter_pereval_added_autumn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pereval_images',
            old_name='author',
            new_name='id_perevala',
        ),
    ]
