# Generated by Django 4.1.5 on 2023-01-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0006_rename_author_pereval_images_id_perevala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval_added',
            name='beautyTitle',
            field=models.TextField(blank=True, max_length=25, verbose_name='Красивое название'),
        ),
        migrations.AlterField(
            model_name='pereval_added',
            name='connect',
            field=models.TextField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='pereval_added',
            name='other_titles',
            field=models.TextField(blank=True, max_length=25, verbose_name='Другие комментарии'),
        ),
    ]
