# Generated by Django 4.1.5 on 2023-01-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0007_alter_pereval_added_beautytitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='emails',
            field=models.EmailField(max_length=30, verbose_name='Почта пользователя'),
        ),
    ]
