# Generated by Django 4.1.5 on 2023-01-09 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0008_alter_users_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval_added',
            name='area',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pereval.pereval_areas', verbose_name='Горный хребет'),
        ),
        migrations.AlterField(
            model_name='users',
            name='emails',
            field=models.EmailField(max_length=30, unique=True, verbose_name='Почта пользователя'),
        ),
    ]
