# Generated by Django 4.1.5 on 2023-01-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0009_alter_pereval_added_area_alter_users_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pereval_added',
            name='area',
        ),
    ]
