# Generated by Django 4.1.5 on 2023-01-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0010_remove_pereval_added_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='emails',
            field=models.EmailField(max_length=30, verbose_name='Почта пользователя'),
        ),
    ]
