# Generated by Django 4.1.5 on 2023-01-09 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0012_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval_added',
            name='coord_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pereval.coords'),
        ),
    ]
