# Generated by Django 4.1.5 on 2023-01-09 15:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0013_alter_pereval_added_coord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='emails',
            field=models.EmailField(max_length=30, unique=True, verbose_name='Почта пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
